# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Its
                   \n
                   Neuronal"
tagline:          'An occasionally updated blog'
description:      'An occasionally updated blog.'
url:              http://alexhwilliams.info
baseurl:          /itsneuronalblog/
baseurl_:         /itsneuronalblog

markdown: kramdown

kramdown:
  input: GFM
  highlighter: pygments
  enable_coderay: true

author:
  name:           'Alex Williams'
  url:            http://alexhwilliams.info

paginate: 10
excerpt_separator: <!--more-->

plugins: ['jekyll-paginate']

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ahwillia/itsneuronalblog
