# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            "Its
                   \n
                   Neuronal"
tagline:          'Math and Computation in Neuoscience'
description:      'A blog on math and computation in neuroscience.'
url:              http://alexhwilliams.info
baseurl:          /itsneuronalblog/
baseurl_:         /itsneuronalblog

markdown: kramdown

kramdown:
  input: GFM
  highlighter: pygments
  use_coderay: true
  enable_coderay: true

author:
  name:           'Alex Williams'
  url:            http://alexhwilliams.info

paginate: 10
excerpt_separator: <!--more-->

# gems: ['jekyll-twitter-plugin']

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ahwillia/quantneuro